version: '3'
services:
  backend:
    image: module-name:1.0.0
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    ports:
      - "81:8080"
  frontend2:
    build:
      context: ./frontend2
    ports:
      - "82:8080"