FROM openjdk:11-jre-slim
WORKDIR /app

# Copy the compiled JAR from the target directory into the container
COPY backend/target/backend-1.0.0.jar app.jar

# Command to run the application
CMD ["java", "-jar", "app.jar"]
