# Use an image with the full JDK instead of just the JRE
FROM openjdk:11
# Install Maven
RUN apt-get update && apt-get install -y maven
# Copy the source code into the container
COPY / /usr/src/backend/
# Set the working directory
WORKDIR /usr/src/backend/
RUN mvn clean install
# Specify the command to run your Spring Boot application
CMD ["mvn","spring-boot:run"]
